language: node_js
node_js:
  - lts/*
  - 16
  - 14
  - 12
script: echo "Running tests against $(node -v) ..."
jobs:
  include:
    - stage: npm release
      node_js: lts/*
      script: echo "Deploying to npm..."
      before_deploy: "yarn"    
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_APIKEY
        on: deploy-npm-release
